#:schema ./node_modules/wrangler/config-schema.json
name = "aiaio"
main = "./worker/index.ts"
compatibility_date = "2026-01-11"
compatibility_flags = ["nodejs_als"]
workers_dev = true

[observability]
enabled = true

[observability.traces]
enabled = true
