#:schema ./node_modules/wrangler/config-schema.json
name = "aiaio"
main = "./worker/index.tsx"
compatibility_date = "2026-01-19"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
upload_source_maps = true

[observability]
enabled = true

[observability.traces]
enabled = true

[assets]
binding = "ASSETS"

[browser]
binding = "BROWSER"
